name: automerge
on: workflow_dispatch 

jobs:
  merge:
    name: "Merge"

    runs-on: "ubuntu-latest"

    steps:
      - name: "check PRs"
        uses: "actions/github-script@v6"
        with:
          github-token: " ${{ secrets.GITHUB_TOKEN }}"
          script: |
            function handlePull(pull) {
              const number = pull.number
              const user = pull.user.login
              const labels = pull.labels
              const draft = pull.draft
          
              const full = octokit.rest.pulls.get({
                owner,
                repo,
                number,
              }).then(console.log(full));
          
            }
          
            const repo = context.repo
            const owner = context.owner
            const pulls = github.rest.pulls.list({
              owner: owner,
              repo: repo,
              state: "open",
            });

            if(pulls.length > 0){
              pulls.data.forEach(handlePull);
            } else {
              console.log("no open pull requests");
            }            
