name: automerge
on: workflow_dispatch 

jobs:
  merge:
    name: "Merge"

    runs-on: "ubuntu-latest"

    steps:
      - name: "check PRs"
        uses: "actions/github-script@v6"
        with:
          github-token: " ${{ secrets.GITHUB_TOKEN }}"
          script: |
            const repo = context.repo
            const owner = context.owner
            const state = "open";

            function deleteBranch(branch){
              github.request("DELETE /repos/${owner}/${repo}/git/refs/heads/${branch}").then(console.log("Branch deleted: "+branch));
            }

            function handleChecked(branch, number, checks){
              const checks_list = checks.check_runs;
              
              if(checks_list.length == 2 && checks_list[0].conclusion == "success" && checks_list[1].conclusion == "success" ){
                console.log("Merge PR "+number);
                github.request("PUT /repos/${owner}/${repo}/pulls/${number}/merge").then(deleteBranch(branch));
              }
                
            }

            function handlePull(pull) {
              const number = pull.number;
              const user = pull.user.login;
              const labels = pull.labels;
              const draft = pull.draft;
              const commit = pull.head.sha;
              const branch = pull.head.ref;

              if(user == "github-actions[bot]" && labels.length == 1 && labels[0].name == 'auto-pr' && draft == false){
                console.log("Check PR "+number);
                github.request("GET /repos/${owner}/${repo}/commits/${commit}/check-runs").then(detail => handleChecked(branch, number, detail.data));
              } 
            }

            async function processPulls() {
                
              const pulls = await github.rest.pulls.list({
                owner,
                repo,
                state,
              });
              
              if(pulls.data.length > 0){
                pulls.data.forEach(handlePull);
              } else {
                console.log("no open pull requests");
              }

            }

            processPulls().then(console.log("processing pull requests finished"));
