name: automerge
on: workflow_dispatch 

jobs:
  merge:
    name: "Merge"

    runs-on: "ubuntu-latest"

    steps:
      - name: "check PRs"
        uses: "actions/github-script@v6"
        with:
          github-token: " ${{ secrets.GITHUB_TOKEN }}"
          script: |
            const repo = context.repo
            const owner = context.owner
            const pullRequests = github.rest.pulls.list({
                owner,
                repo,
                'open'
            });
            
            console.log(pullRequests)
