# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: maven-build

concurrency: build

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@cbe522639944d3247f1f8832639650558051f9b7
      with:
        egress-policy: block

    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      with:
        fetch-depth: '0'
    
    - name: Set up JDK 17
      uses: actions/setup-java@ea15b3b99cdc9ac45af1882d085e3f9297a75a8b
      with:
        java-version: 17
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@e0d62270e20d6eeecf2fd6397a1b8871b6269e38
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Cache SonarCloud packages
      uses: actions/cache@e0d62270e20d6eeecf2fd6397a1b8871b6269e38
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    
    # Next step will start build & deploy maven site with additional artifacts for the Maven site
    - name: Build and analyze dev
      run: |
        git config --global user.email "jens.dibbern@gmail.com"
        git config --global user.name "datengaertnerei"
        export OSM_IMPORT_FILE=https://github.com/datengaertnerei/test-data-service/raw/develop/data/osm-small.pbf
        mvn -B deploy site org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        npm install --global @cyclonedx/cyclonedx-npm
        cyclonedx-npm --output-file target/site/frontend-sbom.json --ignore-npm-errors src/app/package.json
        mkdir ~/site-tmp
        cp -r target/site/* ~/site-tmp
        cp -r target/test-data-service-oas.json ~/site-tmp
        cp -r target/test-data-service-bom.* ~/site-tmp
        git stash
        git checkout gh_pages
        cp -r ~/site-tmp/* docs
        git add -A docs
        git commit docs -m "Maven Site generated"
        git push
        rm -rf ~/site-tmp
        git checkout develop
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
    - uses: codecov/codecov-action@4b062cb89c1fe1fd7da7e013d554a088ea14178a