# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: maven-build

concurrency: build

on:
  push:
    branches: [ develop, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@b4401455ef773683d2da2e176e3539cce0fabdc7
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@5c3ccc22eb2c950a0fa5bc7c47190d8e3f7e681a
      with:
        fetch-depth: '0'
    
    - name: Set up JDK 17
      uses: actions/setup-java@de1bb2b0c5634f0fc4438d7aa9944e68f9bf86cc
      with:
        java-version: 17
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@9a6a4f6079716b44e70b2e883cfdd6fb7d6ff5d9
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Cache SonarCloud packages
      uses: actions/cache@9a6a4f6079716b44e70b2e883cfdd6fb7d6ff5d9
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    
    - name: Build and analyze dev
      if: ${{ github.ref == 'refs/heads/develop' }}
      run: |
        git config --global user.email "jens.dibbern@gmail.com"
        git config --global user.name "datengaertnerei"
        export OSM_IMPORT_FILE=https://github.com/datengaertnerei/test-data-service/raw/develop/data/osm-small.pbf
        mvn -B deploy site org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        mkdir ~/site-tmp
        cp -r target/site/* ~/site-tmp
        cp -r target/test-data-service-oas.json ~/site-tmp
        cp -r target/test-data-service-bom.* ~/site-tmp
        git stash
        git checkout gh_pages
        cp -r ~/site-tmp/* docs
        git add -A docs
        git commit docs -m "Maven Site generated"
        git push
        rm -rf ~/site-tmp
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Build and analyze main
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        export OSM_IMPORT_FILE=https://github.com/datengaertnerei/test-data-service/raw/develop/data/osm-small.pbf
        mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}        
        
    - uses: codecov/codecov-action@e0fbd592d323cb2991fb586fdd260734fcb41fcb