# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: maven-build

concurrency: build

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@6dacdfc16caa5ebd987908a44ab5b425193385f6
      with:
        disable-sudo: true
        egress-policy: audit #sonarcloud aws generic hostname unfortunately subject to change

    - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      with:
        fetch-depth: '0'
    
    - name: Set up JDK 17
      uses: actions/setup-java@ddb82ce8a6ecf5ac3e80c3184839e6661546e4aa
      with:
        java-version: 17
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@04f198bf0b2a39f7230a4304bf07747a0bddf146
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Cache SonarCloud packages
      uses: actions/cache@04f198bf0b2a39f7230a4304bf07747a0bddf146
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    
    # Next step will start build & deploy maven site with additional artifacts for the Maven site
    - name: Build and analyze dev
      run: |
        git config --global user.email "jens.dibbern@gmail.com"
        git config --global user.name "datengaertnerei"
        mvn -B dependency:list -DoutputAbsoluteArtifactFilename=true -DoutputFile=dependency-list.txt -Dsilent=true
        export OSM_IMPORT_FILE=https://github.com/datengaertnerei/test-data-service/raw/develop/data/osm-small.pbf
        export MAVEN_OPTS="-verbose:class"
        touch ./mvn-build.log
        tail -f ./mvn-build.log &
        mvn -B --log-file ./mvn-build.log deploy site org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dorg.slf4j.simpleLogger.defaultLogLevel=warn > classloader.log
        cp ./mvn-build.log target/site/mvn-build.log.txt
        cp ./classloader.log target/site/classloader.log.txt
        cp ./dependency-list.txt target/site/dependency-list.txt
        npm install --global @cyclonedx/cyclonedx-npm
        cyclonedx-npm --output-file target/site/frontend-sbom.json --ignore-npm-errors src/app/package.json
        mkdir ~/site-tmp
        cp -r target/site/* ~/site-tmp
        cp -r target/test-data-service-oas.json ~/site-tmp
        cp -r target/test-data-service-bom.* ~/site-tmp
        git stash
        git checkout gh_pages
        cp -r ~/site-tmp/* docs
        git add -A docs
        git commit docs -m "Maven Site generated"
        git push
        rm -rf ~/site-tmp
        git checkout develop
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
    - uses: codecov/codecov-action@1dd0ce34be62fac4f3b714f860c0b0c520acd35d