# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: maven-build

concurrency: build

on:
  push:
    branches: [ develop, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@cdea734fa57747b9831aa9d6fcb274c5f9669557
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      with:
        fetch-depth: '0'
    
    - name: Set up JDK 17
      uses: actions/setup-java@16cca5479d7c6b6843f6a6515640ba33c6501543
      with:
        java-version: 17
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@eec8cd3f5f6c5051d6f6977ae774b9ede9fd39ef
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Cache SonarCloud packages
      uses: actions/cache@eec8cd3f5f6c5051d6f6977ae774b9ede9fd39ef
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    
    - name: Build and analyze dev
      if: ${{ github.ref == 'refs/heads/develop' }}
      run: |
        git config --global user.email "jens.dibbern@gmail.com"
        git config --global user.name "datengaertnerei"
        export OSM_IMPORT_FILE=https://github.com/datengaertnerei/test-data-service/raw/develop/data/osm-small.pbf
        mvn -B deploy site org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        mkdir ~/site-tmp
        cp -r target/site/* ~/site-tmp
        cp -r target/test-data-service-oas.json ~/site-tmp
        cp -r target/test-data-service-bom.* ~/site-tmp
        git stash
        git checkout gh_pages
        cp -r ~/site-tmp/* docs
        git add -A docs
        git commit docs -m "Maven Site generated"
        git push
        rm -rf ~/site-tmp
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Build and analyze main
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        export OSM_IMPORT_FILE=https://github.com/datengaertnerei/test-data-service/raw/develop/data/osm-small.pbf
        mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}        
        
    - uses: codecov/codecov-action@8e09eaf1b47fbb5da0e32a27bf08cd11929a1b4a