name: docker

on: 
  workflow_dispatch
#  schedule:
    # * is a special character in YAML so you have to quote this string
#    - cron:  '0 2 15 * *'
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@8e0b4153524c217e5dce81df0986478e95a7004a
      with:
        disable-sudo: true
        egress-policy: audit #outbound hosts constantly subject to change by action providers
      
    - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
    
    - name: Set up JDK 17
      uses: actions/setup-java@191ba8c6ba49737c558c820f47161f35b262c87d
      with:
        java-version: 17
        distribution: 'temurin'
                
    - name: Download Maven release
      id: mvnrel
      run: |
        git config --global user.email "jens.dibbern@gmail.com"
        git config --global user.name "datengaertnerei"
        export MVNVER=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-SNAPSHOT//')
        export RELBRANCH="RB-${MVNVER}"
        mvn dependency:copy \
            -Dartifact=com.datengaertnerei.test:data-service:1.0.7 \
            -DoutputDirectory=. \
            --global-settings .github/settings.xml
        # preserve branch and tag info
        echo ::set-output name=release_branch::$RELBRANCH
        echo ::set-output name=releasetag::V${MVNVER}
        echo ::set-output name=prsource::$PRSOURCE
      env:        
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        