name: docker

on: 
  workflow_dispatch
#  schedule:
    # * is a special character in YAML so you have to quote this string
#    - cron:  '0 2 15 * *'
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@910b3276b25495e4cfd8669cf5d7ea16508b0241
      with:
        disable-sudo: true
        egress-policy: audit #outbound hosts constantly subject to change by action providers
      
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        fetch-depth: '0'
        ref: master
    
    - name: Set up JDK 17
      uses: actions/setup-java@ddb82ce8a6ecf5ac3e80c3184839e6661546e4aa
      with:
        java-version: 17
        distribution: 'temurin'
                
    - name: Download Maven release
      id: mvnrel
      run: |
        git config --global user.email "jens.dibbern@gmail.com"
        git config --global user.name "datengaertnerei"
        export MVNVER=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-SNAPSHOT//')
        export RELBRANCH="RB-${MVNVER}"
        mvn dependency:copy \
            -Dartifact=com.datengaertnerei.test:data-service:${MVNVER} \
            -DoutputDirectory=. \
            --global-settings .github/settings.xml
        # preserve branch and tag info
        echo "release_branch=$RELBRANCH" >> $GITHUB_OUTPUT
        echo "releasetag=V${MVNVER}" >> $GITHUB_OUTPUT
        echo "prsource=$PRSOURCE" >> $GITHUB_OUTPUT
      env:        
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        