name: docker

on: 
  workflow_call:
#  schedule:
    # * is a special character in YAML so you have to quote this string
#    - cron:  '0 5 15 * *'
    
jobs:
  docker:

    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7
      with:
        disable-sudo: true
        egress-policy: audit #outbound hosts constantly subject to change by action providers
      
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        fetch-depth: '0'
        ref: master
    
    - name: Set up JDK 21
      uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b
      with:
        java-version: 21
        distribution: 'temurin'
                
    - name: Download Maven release
      id: mvnrel
      run: |
        git config --global user.email "jens.dibbern@gmail.com"
        git config --global user.name "datengaertnerei"
        mkdir -p target
        export MVNVER=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-SNAPSHOT//')
        ./mvnw dependency:copy \
            -Dartifact=com.datengaertnerei.test:data-service:${MVNVER} \
            -DoutputDirectory=target \
            --global-settings .github/settings.xml
        # preserve branch and tag info
        echo "dockertag=${MVNVER}" >> $GITHUB_OUTPUT
      env:        
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .      
        push: true
        tags: |
          datengaertner/test-data-service:latest
          datengaertner/test-data-service:${{steps.mvnrel.outputs.dockertag}}