# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: maven-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B deploy --file pom.xml
      env:        
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Increment patch number
      run: mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} versions:commit 
    - name: Commit POM
      run: |
        git config --global user.name 'Jens Dibbern'
        git config --global user.email 'datengaertnerei@users.noreply.github.com'
        git commit -m "Action commit" pom.xml
        git push      
      env:        
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/delete-package-versions@v1
      with:
        package-name: 'com.datengaertnerei.test.data-service'
        num-old-versions-to-delete: 1