# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: maven-merge-check

on:
  pull_request:

permissions: read-all

jobs:
  build:
    name: merge status check

    runs-on: ubuntu-latest

    permissions:
      # required for all workflows
      security-events: write
            
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0f3c98aa98444b3a4e8eb1b5ecc20a7ea24d932d
      with:
        disable-sudo: true
        egress-policy: audit #outbound hosts constantly subject to change by action providers
        
    - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
    - name: Set up JDK 21
      uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12
      with:
        java-version: 21
        distribution: 'temurin'

      # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@8c69433c34fe91b0644d83e6f14bb77eb3e46812
      with:
        languages: javascript, python, java        
        
    - name: Build with Maven
      run: |
        export OSM_IMPORT_FILE=https://github.com/datengaertnerei/test-data-service/raw/develop/data/osm-small.pbf
        ./mvnw -B test --file pom.xml
      env:        
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@8c69433c34fe91b0644d83e6f14bb77eb3e46812