# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: maven-merge-check

on:
  pull_request:

permissions: read-all

jobs:
  build:
    name: merge status check

    runs-on: ubuntu-latest

    permissions:
      # required for all workflows
      security-events: write
            
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911
      with:
        disable-sudo: true
        egress-policy: audit #outbound hosts constantly subject to change by action providers
        
    - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
    - name: Set up JDK 21
      uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165
      with:
        java-version: 21
        distribution: 'temurin'

      # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@1fd8a71a1271a5ad7639a423fdd9485e1be64031
      with:
        languages: javascript, python, java        
        
    - name: Build with Maven
      run: |
        export OSM_IMPORT_FILE=https://github.com/datengaertnerei/test-data-service/raw/develop/data/osm-small.pbf
        ./mvnw -B test --file pom.xml
      env:        
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@1fd8a71a1271a5ad7639a423fdd9485e1be64031