# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: maven-merge-check

concurrency: merge-check

on:
  pull_request:

permissions: read-all

jobs:
  build:
    name: merge status check

    runs-on: ubuntu-latest

    permissions:
      # required for all workflows
      security-events: write
            
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@40a26682a9fb0236b09d568ab43f35c95881fff6
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          files.pythonhosted.org:443
          github.com:443
          playwright.azureedge.net:443
          pypi.org:443
          raw.githubusercontent.com:443
          registry.npmjs.org:443
          registry.yarnpkg.com:443
          repo.maven.apache.org:443
          repo.spring.io:443
          www.google-analytics.com:443
        
    - uses: actions/checkout@27135e314dd1818f797af1db9dae03a9f045786b
    - name: Set up JDK 17
      uses: actions/setup-java@888b4006f39f9718dc69efb685c48e14340507b6
      with:
        java-version: 17
        distribution: 'temurin'

      # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@19f00dc212364caec77c5ea88fa53cb5deebc752
      with:
        languages: javascript, python, java        
        
    - name: Build with Maven
      run: |
        export OSM_IMPORT_FILE=https://github.com/datengaertnerei/test-data-service/raw/develop/data/osm-small.pbf
        mvn -B test --file pom.xml
      env:        
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@19f00dc212364caec77c5ea88fa53cb5deebc752