# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: maven-merge-check

on:
  pull_request:

permissions: read-all

jobs:
  build:
    name: merge status check

    runs-on: ubuntu-latest

    permissions:
      # required for all workflows
      security-events: write
            
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@c0db65e1f64025718795419be8dbbf8c4050160f
      with:
        disable-sudo: true
        egress-policy: audit #outbound hosts constantly subject to change by action providers
        
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - name: Set up JDK 17
      uses: actions/setup-java@16ef37f8dd292a31055a9ee0d26fa0a4efab58de
      with:
        java-version: 17
        distribution: 'temurin'

      # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@382a50a0284c0de445104889a9d6003acb4b3c1d
      with:
        languages: javascript, python, java        
        
    - name: Build with Maven
      run: |
        export OSM_IMPORT_FILE=https://github.com/datengaertnerei/test-data-service/raw/develop/data/osm-small.pbf
        mvn -B test --file pom.xml
      env:        
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@382a50a0284c0de445104889a9d6003acb4b3c1d