# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: maven-merge-check

on:
  pull_request:

permissions: read-all

jobs:
  build:
    name: merge status check

    runs-on: ubuntu-latest

    permissions:
      # required for all workflows
      security-events: write
            
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7
      with:
        disable-sudo: true
        egress-policy: audit #outbound hosts constantly subject to change by action providers
        
    - uses: actions/checkout@6d193bf28034eafb982f37bd894289fe649468fc
    - name: Set up JDK 21
      uses: actions/setup-java@2dfa2011c5b2a0f1489bf9e433881c92c1631f88
      with:
        java-version: 21
        distribution: 'temurin'

      # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@e817992b3db357f199b6e99216d3bf853dafd0fc
      with:
        languages: javascript, python, java        
        
    - name: Build with Maven
      run: |
        export OSM_IMPORT_FILE=https://github.com/datengaertnerei/test-data-service/raw/develop/data/osm-small.pbf
        ./mvnw -B test --file pom.xml
      env:        
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@e817992b3db357f199b6e99216d3bf853dafd0fc