# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: maven-merge-check

on:
  pull_request:

permissions: read-all

jobs:
  build:
    name: merge status check

    runs-on: ubuntu-latest

    permissions:
      # required for all workflows
      security-events: write
            
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@910b3276b25495e4cfd8669cf5d7ea16508b0241
      with:
        disable-sudo: true
        egress-policy: audit #outbound hosts constantly subject to change by action providers
        
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
    - name: Set up JDK 17
      uses: actions/setup-java@ddb82ce8a6ecf5ac3e80c3184839e6661546e4aa
      with:
        java-version: 17
        distribution: 'temurin'

      # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@ed6c4995fcfc90fa1e870bf955dd15e010cf71e8
      with:
        languages: javascript, python, java        
        
    - name: Build with Maven
      run: |
        export OSM_IMPORT_FILE=https://github.com/datengaertnerei/test-data-service/raw/develop/data/osm-small.pbf
        mvn -B test --file pom.xml
      env:        
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@ed6c4995fcfc90fa1e870bf955dd15e010cf71e8