# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: create-pr-dev-main

concurrency: dev-build

on: workflow_dispatch
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'temurin'
                
    - name: Create PR
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master"
        pr_title: "Pulling ${{ github.ref }} into main"
        pr_body: "automated PR"
        pr_reviewer: "gh action"
        pr_draft: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Increment patch number for next release
      run: mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT versions:commit 
      
    - name: Commit POM
      run: |
        git config --local user.email "$(git log --format='%ae' HEAD^!)"
        git config --local user.name "$(git log --format='%an' HEAD^!)"
        git commit -m "Action commit: increase SemVer" pom.xml
        git push      
      env:        
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
