# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: maven-release-pr

concurrency: dev-build

on: workflow_dispatch
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'temurin'
                
    - name: Create PR
      uses: devops-infra/action-pull-request@v0.4.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source_branch: development
        target_branch: master
        title: "Release"
        draft: true
        get_diff: true

    - name: Increment patch number for next release
      run: mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT versions:commit 
      
    - name: Commit POM
      run: |
        git config --local user.email "$(git log --format='%ae' HEAD^!)"
        git config --local user.name "$(git log --format='%an' HEAD^!)"
        git commit -m "Action commit: increase SemVer" pom.xml
        git push      
      env:        
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
