name: scheduled-merge

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 4 * * *'
    
jobs:
  start-release:
    uses: datengaertnerei/test-data-service/.github/workflows/automerge.yml@develop
    secrets: inherit